In [ ]:
import pandas as pd
import numpy as np

import geopandas as gpd
from shapely.geometry import Point, box

from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 모든 컬럼을 출력하도록 설정
pd.set_option('display.max_columns', None)  # 모든 컬럼 표시
pd.set_option('display.max_rows', None)     # 모든 행 표시

In [ ]:
## raw데이터

HS_거주인구 = pd.read_csv('/content/drive/MyDrive/1-1.화성시_거주인구.csv')
HS_추정교통량 = pd.read_csv('/content/drive/MyDrive/1-2.화성시_추정교통량.csv')
HS_상세도로망 = gpd.read_file('/content/drive/MyDrive/1-3.화성시_상세도로망.geojson') # .geojson
HS_상권정보 = pd.read_csv('/content/drive/MyDrive/1-4.화성시_상권정보.csv')
HS_버스정류장 = pd.read_csv('/content/drive/MyDrive/1-5.화성시_버스정류장.csv')
HS_지하철역 = pd.read_csv('/content/drive/MyDrive/1-6.화성시_지하철역.csv')
HS_공영주차장 = pd.read_csv('/content/drive/MyDrive/1-7.화성시_공영주차장.csv')
HS_격자 = gpd.read_file('/content/drive/MyDrive/1-14.화성시_격자.geojson') # .geojson

HN_거주인구 = pd.read_csv('/content/drive/MyDrive/2-1.하남시_거주인구.csv')
HN_추정교통량 = pd.read_csv('/content/drive/MyDrive/2-2.하남시_추정교통량.csv')
HN_상세도로망 = gpd.read_file('/content/drive/MyDrive/2-3.하남시_상세도로망.geojson') # .geojson
HN_상권정보 = pd.read_csv('/content/drive/MyDrive/2-4.하남시_상권정보.csv')
HN_버스정류장 = pd.read_csv('/content/drive/MyDrive/2-5.하남시_버스정류장.csv')
HN_지하철역 = pd.read_csv('/content/drive/MyDrive/2-6.하남시_지하철역.csv')
HN_공영주차장 = pd.read_csv('/content/drive/MyDrive/2-7.하남시_공영주차장.csv')
HN_격자 = gpd.read_file('/content/drive/MyDrive/2-14.하남시_격자.geojson') # .geojson


HS_raw = [HS_거주인구, HS_추정교통량, HS_상세도로망, HS_상권정보,
      HS_버스정류장, HS_지하철역, HS_공영주차장, HS_격자]

HN_raw = [HN_거주인구, HN_추정교통량, HN_상세도로망, HN_상권정보,
      HN_버스정류장, HN_지하철역, HN_공영주차장, HN_격자]

HS_raw_n = ['HS_거주인구', 'HS_추정교통량', 'HS_상세도로망', 'HS_상권정보',
      'HS_버스정류장', 'HS_지하철역', 'HS_공영주차장', 'HS_격자']

HN_raw_n = ['HN_거주인구', 'HN_추정교통량', 'HN_상세도로망', 'HN_상권정보',
      'HN_버스정류장', 'HN_지하철역', 'HN_공영주차장', 'HN_격자']

<ipython-input-81-3778c5351cd6>:4: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  HS_추정교통량 = pd.read_csv('/content/drive/MyDrive/1-2.화성시_추정교통량.csv')
<ipython-input-81-3778c5351cd6>:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  HN_추정교통량 = pd.read_csv('/content/drive/MyDrive/2-2.하남시_추정교통량.csv')

In [ ]:
## 반출데이터(은서)

# 공공주택 유형별 데이터
HS_공공 = pd.read_csv('/content/화성시_공공임대.csv')
HS_영구 = pd.read_csv('/content/화성시_영구임대.csv')
HS_행복 = pd.read_csv('/content/화성시_행복주택.csv')
HS_국민 = pd.read_csv('/content/화성시_국민임대.csv')

HN_공공 = pd.read_csv('/content/하남시_공공임대.csv')
HN_영구 = pd.read_csv('/content/하남시_영구임대.csv')
HN_행복 = pd.read_csv('/content/하남시_행복주택.csv')
HN_국민 = pd.read_csv('/content/하남시_국민임대.csv')

HS_공공주택 = [HS_공공, HS_국민, HS_영구, HS_행복]
HS_공공주택_n = ['HS_공공', 'HS_국민', 'HS_영구', 'HS_행복']

HN_공공주택 = [HN_공공, HN_국민, HN_영구, HN_행복]
HN_공공주택_n = ['HN_공공', 'HN_국민', 'HN_영구', 'HN_행복']


# 그 외 반출데이터
HS_공유차량_거주인구 = pd.read_csv('/content/화성시_공유차량_거주인구.csv')
HS_공공주택_임대료 = pd.read_csv('/content/화성시_공공주택_임대료.csv')
HS_공유차량_공공주택 = pd.read_csv('/content/화성시_공유차량_공공주택.csv')
#HS_추정교통량_상세도로망 = pd.read_csv('/content/화성시_추정교통량_상세도로망.csv')
#HS_성별_유동인구 = pd.read_csv('/content/화성시_성별_유동인구.csv')

HN_공유차량_거주인구 = pd.read_csv('/content/하남시_공유차량_거주인구.csv',encoding='cp949')
HN_공공주택_임대료 = pd.read_csv('/content/하남시_공공주택_임대료.csv')
HN_공유차량_공공주택 = pd.read_csv('/content/하남시_공유차량_공공주택.csv')
#HN_추정교통량_상세도로망 = pd.read_csv('/content/하남시/하남시_추정교통량_상세도로망.csv')
#HN_성별_유동인구 = pd.read_csv('/content/하남시_성별_유동인구.csv')


#HS = [ HS_공유차량_거주인구, HS_공공주택_임대료, HS_공유차량_공공주택, HS_추정교통량_상세도로망, HN_성별_유동인구]
#HS_n = [ 'HS_공유차량_거주인구', 'HS_공공주택_임대료', 'HS_공유차량_공공주택', 'HS_추정교통량_상세도로망', 'HS_성별_유동인구']

#HN = [ HN_공유차량_거주인구, HN_공공주택_임대료, HN_공유차량_공공주택, HN_추정교통량_상세도로망, HN_성별_유동인구]
#HN_n = [ 'HN_공유차량_거주인구', 'HN_공공주택_임대료', 'HN_공유차량_공공주택', 'HN_추정교통량_상세도로망', 'HN_성별_유동인구']

# 1차  데이터 시작

In [ ]:
def Lon_Lat(df):
    df['geometry'] = df.apply(lambda row: Point(row['lon'], row['lat']), axis=1)
    df = gpd.GeoDataFrame(df, geometry='geometry')
    return df

HS_공공 = Lon_Lat(HS_공공)
HS_영구 = Lon_Lat(HS_영구)
HS_행복 = Lon_Lat(HS_행복)
HS_국민 = Lon_Lat(HS_국민)

HN_공공 = Lon_Lat(HN_공공)
HN_영구 = Lon_Lat(HN_영구)
HN_행복 = Lon_Lat(HN_행복)
HN_국민 = Lon_Lat(HN_국민)

In [ ]:
buffer_size = 0.01  # 버퍼 크기 설정

# 거주 인구 -> 성별, 운전 가능, 운전 위험, 총 인구 수

In [ ]:
## 거주인구 데이터 처리
# 결측값 처리
HS_공유차량_거주인구 = HS_공유차량_거주인구.fillna(0)
HN_공유차량_거주인구 = HN_공유차량_거주인구.fillna(0)

# GeoDataFrame 변환
HS_공유차량_거주인구['geometry'] = HS_공유차량_거주인구.apply(lambda row: Point(row['x'], row['y']), axis=1)
HS_공유차량_거주인구 = gpd.GeoDataFrame(HS_공유차량_거주인구, geometry='geometry')

HN_공유차량_거주인구['geometry'] = HN_공유차량_거주인구.apply(lambda row: Point(row['x'], row['y']), axis=1)
HN_공유차량_거주인구 = gpd.GeoDataFrame(HN_공유차량_거주인구, geometry='geometry')

def aggregate_population_data(df):
    # 'pop'으로 끝나는 컬럼 선택
    pop_columns = [col for col in df.columns if col.endswith('pop')]

    # field_1 기준으로 합산
    aggregated = df.groupby(['field_1', 'year'])[pop_columns].sum().reset_index()

    return aggregated

# 두 데이터셋 처리
HS_공유차량_거주인구= aggregate_population_data(HS_공유차량_거주인구)
HN_공유차량_거주인구= aggregate_population_data(HN_공유차량_거주인구)

In [ ]:
HS_공유차량_거주인구 = HS_공유차량_거주인구[HS_공유차량_거주인구['total_pop'] != 0]
HN_공유차량_거주인구 = HN_공유차량_거주인구[HN_공유차량_거주인구['total_pop'] != 0]

In [ ]:
HS_공유차량_거주인구

,field_1,year,m_20g_pop,w_20g_pop,m_30g_pop,w_30g_pop,m_40g_pop,w_40g_pop,m_50g_pop,w_50g_pop,m_60g_pop,w_60g_pop,m_70g_pop,w_70g_pop,m_80g_pop,w_80g_pop,m_90g_pop,w_90g_pop,m_100g_pop,w_100g_pop,total_pop
0,0,2020,67.0,70.0,165.0,72.0,126.0,60.0,99.0,68.0,96.0,71.0,26.0,32.0,0.0,10.0,0.0,0.0,0.0,0.0,962.0
1,0,2021,58.0,64.0,178.0,83.0,138.0,54.0,112.0,66.0,99.0,76.0,33.0,34.0,12.0,13.0,0.0,0.0,0.0,0.0,1020.0
2,0,2022,44.0,60.0,153.0,94.0,130.0,48.0,112.0,70.0,108.0,78.0,37.0,30.0,0.0,12.0,0.0,0.0,0.0,0.0,976.0
3,0,2023,36.0,57.0,152.0,91.0,122.0,51.0,109.0,67.0,104.0,82.0,40.0,37.0,6.0,11.0,0.0,0.0,0.0,0.0,965.0
4,1,2020,51.0,63.0,117.0,63.0,102.0,78.0,83.0,107.0,112.0,122.0,48.0,54.0,6.0,23.0,0.0,0.0,0.0,0.0,1029.0
5,1,2021,60.0,63.0,125.0,60.0,100.0,74.0,86.0,96.0,121.0,142.0,51.0,44.0,7.0,29.0,0.0,0.0,0.0,0.0,1058.0
6,1,2022,51.0,44.0,118.0,68.0,109.0,78.0,84.0,100.0,118.0,148.0,52.0,49.0,6.0,30.0,0.0,0.0,0.0,0.0,1055.0
7,1,2023,30.0,30.0,93.0,53.0,105.0,68.0,95.0,84.0,104.0,145.0,58.0,64.0,6.0,27.0,0.0,0.0,0.0,0.0,962.0
8,2,2020,47.0,34.0,116.0,77.0,85.0,52.0,64.0,75.0,87.0,83.0,28.0,25.0,7.0,9.0,0.0,0.0,0.0,0.0,789.0
9,2,2021,44.0,36.0,129.0,68.0,86.0,68.0,74.0,66.0,92.0,88.0,28.0,30.0,6.0,13.0,0.0,0.0,0.0,0.0,828.0
10,2,2022,37.0,23.0,105.0,74.0,97.0,63.0,59.0,67.0,95.0,81.0,38.0,37.0,6.0,7.0,0.0,0.0,0.0,0.0,789.0
11,2,2023,21.0,14.0,57.0,37.0,63.0,37.0,45.0,45.0,76.0,50.0,32.0,27.0,0.0,6.0,0.0,0.0,0.0,0.0,510.0
12,3,2020,117.0,123.0,121.0,119.0,192.0,242.0,129.0,138.0,86.0,159.0,57.0,102.0,19.0,54.0,8.0,0.0,0.0,0.0,1666.0
13,3,2021,105.0,132.0,115.0,100.0,184.0,233.0,139.0,141.0,94.0,163.0,61.0,117.0,25.0,49.0,8.0,6.0,0.0,0.0,1672.0
14,3,2022,110.0,129.0,106.0,97.0,170.0,210.0,145.0,167.0,98.0,176.0,70.0,117.0,37.0,52.0,6.0,0.0,0.0,0.0,1690.0
15,3,2023,106.0,113.0,97.0,85.0,141.0,171.0,136.0,177.0,101.0,178.0,66.0,119.0,42.0,64.0,0.0,0.0,0.0,0.0,1596.0
16,4,2020,166.0,136.0,270.0,156.0,16.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,754.0
17,4,2021,116.0,110.0,289.0,180.0,33.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,746.0
18,4,2022,89.0,91.0,327.0,176.0,34.0,23.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,746.0
19,4,2023,87.0,92.0,312.0,177.0,39.0,19.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,733.0
20,5,2020,112.0,120.0,165.0,185.0,260.0,228.0,144.0,134.0,78.0,87.0,27.0,25.0,0.0,8.0,0.0,0.0,0.0,0.0,1573.0
21,5,2021,94.0,110.0,143.0,170.0,275.0,241.0,142.0,138.0,98.0,100.0,41.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,1579.0
22,5,2022,95.0,105.0,125.0,153.0,282.0,242.0,151.0,157.0,101.0,101.0,43.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,1587.0
23,5,2023,94.0,104.0,119.0,142.0,264.0,231.0,153.0,150.0,108.0,117.0,47.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,1556.0
24,6,2020,63.0,65.0,164.0,164.0,156.0,126.0,58.0,78.0,50.0,67.0,12.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,1012.0
25,6,2021,67.0,65.0,151.0,169.0,176.0,135.0,59.0,82.0,56.0,76.0,15.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,1060.0
26,6,2022,52.0,65.0,139.0,156.0,184.0,142.0,68.0,85.0,55.0,78.0,20.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,1053.0
27,6,2023,48.0,38.0,96.0,113.0,154.0,133.0,70.0,75.0,46.0,69.0,15.0,13.0,0.0,6.0,0.0,0.0,0.0,0.0,876.0
28,7,2020,109.0,109.0,283.0,266.0,274.0,250.0,106.0,124.0,62.0,63.0,17.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,1688.0
29,7,2021,105.0,95.0,254.0,259.0,319.0,291.0,118.0,139.0,75.0,71.0,7.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,1759.0
30,7,2022,97.0,100.0,210.0,222.0,338.0,316.0,134.0,151.0,77.0,79.0,20.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,1763.0
31,7,2023,94.0,100.0,192.0,205.0,335.0,318.0,146.0,159.0,90.0,82.0,22.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,1765.0
32,8,2020,20.0,34.0,87.0,67.0,24.0,36.0,14.0,33.0,8.0,27.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,356.0
33,8,2021,9.0,26.0,100.0,80.0,29.0,42.0,19.0,34.0,14.0,33.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,392.0
34,8,2022,7.0,22.0,97.0,84.0,29.0,39.0,14.0,40.0,16.0,28.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,388.0
35,8,2023,19.0,23.0,137.0,120.0,73.0,59.0,27.0,58.0,30.0,40.0,10.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,618.0
36,9,2020,42.0,58.0,141.0,123.0,137.0,121.0,53.0,71.0,46.0,48.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,847.0
37,9,2021,36.0,51.0,118.0,113.0,156.0,137.0,56.0,72.0,49.0,55.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,851.0
38,9,2022,42.0,50.0,92.0,98.0,166.0,144.0,67.0,79.0,54.0,59.0,12.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,870.0
39,9,2023,36.0,50.0,91.0,96.0,158.0,141.0,81.0,85.0,54.0,64.0,13.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,875.0
40,10,2020,85.0,98.0,225.0,179.0,157.0,150.0,80.0,109.0,67.0,60.0,11.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,1229.0
41,10,2021,88.0,104.0,236.0,200.0,198.0,175.0,95.0,129.0,71.0,73.0,13.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,1400.0
42,10,2022,68.0,103.0,229.0,185.0,211.0,181.0,101.0,133.0,69.0,87.0,13.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,1397.0
43,10,2023,62.0,89.0,206.0,177.0,221.0,193.0,105.0,130.0,75.0,91.0,23.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,1390.0
44,11,2020,55.0,85.0,163.0,73.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,376.0
45,11,2021,66.0,82.0,168.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,395.0
46,11,2022,69.0,80.0,174.0,92.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,415.0
47,11,2023,77.0,59.0,157.0,77.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,383.0
48,12,2020,39.0,43.0,141.0,104.0,74.0,84.0,57.0,52.0,41.0,81.0,30.0,34.0,0.0,21.0,0.0,0.0,0.0,0.0,801.0
49,12,2021,38.0,44.0,134.0,95.0,88.0,78.0,68.0,62.0,38.0,77.0,28.0,39.0,0.0,23.0,0.0,0.0,0.0,0.0,812.0
50,12,2022,27.0,47.0,117.0,87.0,99.0,67.0,70.0,67.0,51.0,77.0,28.0,49.0,12.0,23.0,0.0,0.0,0.0,0.0,821.0
51,12,2023,29.0,31.0,102.0,81.0,90.0,69.0,72.0,55.0,51.0,74.0,25.0,51.0,14.0,24.0,0.0,0.0,0.0,0.0,768.0
55,13,2023,90.0,125.0,155.0,159.0,105.0,127.0,96.0,119.0,71.0,140.0,86.0,122.0,17.0,36.0,0.0,0.0,0.0,0.0,1448.0
59,14,2023,90.0,125.0,155.0,159.0,105.0,127.0,96.0,119.0,71.0,140.0,86.0,122.0,17.0,36.0,0.0,0.0,0.0,0.0,1448.0
60,15,2020,189.0,226.0,193.0,165.0,14.0,8.0,0.0,0.0,0.0,6.0,6.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,814.0
61,15,2021,294.0,323.0,356.0,295.0,37.0,32.0,9.0,0.0,8.0,19.0,11.0,21.0,0.0,20.0,0.0,0.0,0.0,0.0,1425.0
62,15,2022,235.0,284.0,438.0,300.0,43.0,49.0,10.0,7.0,7.0,19.0,15.0,33.0,0.0,19.0,0.0,0.0,0.0,0.0,1459.0
63,15,2023,191.0,212.0,408.0,273.0,49.0,50.0,10.0,7.0,8.0,15.0,15.0,41.0,0.0,15.0,0.0,0.0,0.0,0.0,1294.0
64,16,2020,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
65,16,2021,114.0,113.0,232.0,152.0,136.0,134.0,91.0,110.0,103.0,123.0,56.0,63.0,0.0,16.0,0.0,0.0,0.0,0.0,1443.0
66,16,2022,127.0,123.0,275.0,166.0,157.0,148.0,118.0,117.0,116.0,135.0,62.0,66.0,7.0,25.0,0.0,0.0,0.0,0.0,1642.0
67,16,2023,89.0,92.0,267.0,172.0,163.0,146.0,119.0,126.0,128.0,136.0,72.0,82.0,0.0,23.0,0.0,0.0,0.0,0.0,1615.0
68,17,2020,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
69,17,2021,114.0,113.0,232.0,152.0,136.0,134.0,91.0,110.0,103.0,123.0,56.0,63.0,0.0,16.0,0.0,0.0,0.0,0.0,1443.0
70,17,2022,127.0,123.0,275.0,166.0,157.0,148.0,118.0,117.0,116.0,135.0,62.0,66.0,7.0,25.0,0.0,0.0,0.0,0.0,1642.0
71,17,2023,89.0,92.0,267.0,172.0,163.0,146.0,119.0,126.0,128.0,136.0,72.0,82.0,0.0,23.0,0.0,0.0,0.0,0.0,1615.0
72,18,2020,110.0,109.0,167.0,77.0,0.0,6.0,0.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,483.0
73,18,2021,105.0,120.0,234.0,118.0,24.0,20.0,0.0,0.0,12.0,9.0,8.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,657.0
74,18,2022,82.0,100.0,239.0,127.0,27.0,14.0,0.0,0.0,12.0,11.0,10.0,13.0,0.0,7.0,0.0,0.0,0.0,0.0,642.0
75,18,2023,87.0,102.0,244.0,137.0,31.0,18.0,0.0,0.0,9.0,12.0,12.0,15.0,0.0,9.0,0.0,0.0,0.0,0.0,676.0
76,19,2020,61.0,90.0,202.0,191.0,182.0,181.0,144.0,139.0,121.0,173.0,103.0,153.0,32.0,60.0,0.0,0.0,0.0,0.0,1832.0
77,19,2021,76.0,97.0,228.0,203.0,199.0,194.0,147.0,136.0,125.0,171.0,106.0,157.0,39.0,77.0,6.0,0.0,0.0,0.0,1961.0
78,19,2022,83.0,91.0,236.0,206.0,203.0,191.0,145.0,147.0,156.0,199.0,110.0,147.0,37.0,83.0,6.0,0.0,0.0,0.0,2040.0
79,19,2023,92.0,71.0,213.0,191.0,201.0,183.0,141.0,159.0,165.0,191.0,115.0,163.0,42.0,84.0,7.0,6.0,0.0,0.0,2024.0
80,20,2020,61.0,90.0,202.0,191.0,182.0,181.0,144.0,139.0,121.0,173.0,103.0,153.0,32.0,60.0,0.0,0.0,0.0,0.0,1832.0
81,20,2021,76.0,97.0,228.0,203.0,199.0,194.0,147.0,136.0,125.0,171.0,106.0,157.0,39.0,77.0,6.0,0.0,0.0,0.0,1961.0
82,20,2022,83.0,91.0,236.0,206.0,203.0,191.0,145.0,147.0,156.0,199.0,110.0,147.0,37.0,83.0,6.0,0.0,0.0,0.0,2040.0
83,20,2023,92.0,71.0,213.0,191.0,201.0,183.0,141.0,159.0,165.0,191.0,115.0,163.0,42.0,84.0,7.0,6.0,0.0,0.0,2024.0
84,21,2020,168.0,210.0,290.0,273.0,365.0,383.0,213.0,279.0,194.0,337.0,136.0,182.0,40.0,76.0,0.0,0.0,0.0,0.0,3146.0
85,21,2021,187.0,200.0,256.0,264.0,358.0,370.0,223.0,283.0,192.0,342.0,142.0,191.0,48.0,104.0,0.0,0.0,0.0,0.0,3160.0
86,21,2022,199.0,203.0,220.0,246.0,348.0,361.0,240.0,298.0,193.0,348.0,152.0,220.0,54.0,115.0,0.0,0.0,0.0,0.0,3197.0
87,21,2023,190.0,176.0,192.0,221.0,304.0,315.0,233.0,310.0,190.0,341.0,159.0,234.0,57.0,106.0,0.0,0.0,0.0,0.0,3028.0
88,22,2020,70.0,52.0,62.0,70.0,136.0,135.0,98.0,98.0,76.0,105.0,38.0,50.0,8.0,34.0,0.0,0.0,0.0,0.0,1032.0
89,22,2021,61.0,48.0,68.0,58.0,116.0,124.0,97.0,99.0,83.0,104.0,44.0,59.0,8.0,37.0,0.0,0.0,0.0,0.0,1006.0
90,22,2022,63.0,52.0,69.0,56.0,107.0,120.0,96.0,100.0,84.0,122.0,47.0,56.0,15.0,38.0,0.0,0.0,0.0,0.0,1025.0
91,22,2023,62.0,46.0,65.0,45.0,101.0,110.0,91.0,99.0,84.0,110.0,43.0,62.0,8.0,38.0,0.0,6.0,0.0,0.0,970.0
92,23,2020,50.0,41.0,63.0,17.0,16.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,205.0
93,23,2021,63.0,39.0,111.0,31.0,29.0,8.0,21.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,310.0
94,23,2022,58.0,31.0,112.0,37.0,28.0,6.0,26.0,7.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,314.0
95,23,2023,54.0,25.0,112.0,34.0,37.0,12.0,28.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,313.0
96,24,2020,34.0,31.0,78.0,54.0,75.0,38.0,43.0,52.0,55.0,66.0,32.0,25.0,0.0,13.0,0.0,0.0,0.0,0.0,596.0
97,24,2021,35.0,25.0,62.0,63.0,74.0,41.0,55.0,52.0,61.0,65.0,26.0,27.0,8.0,13.0,0.0,0.0,0.0,0.0,607.0
98,24,2022,30.0,28.0,68.0,54.0,75.0,49.0,59.0,57.0,62.0,67.0,35.0,33.0,9.0,16.0,0.0,0.0,0.0,0.0,642.0
99,24,2023,24.0,26.0,62.0,46.0,72.0,48.0,55.0,51.0,57.0,75.0,43.0,32.0,0.0,8.0,0.0,0.0,0.0,0.0,599.0
100,25,2020,107.0,85.0,156.0,103.0,137.0,115.0,142.0,131.0,163.0,155.0,59.0,64.0,6.0,14.0,0.0,0.0,0.0,0.0,1437.0
101,25,2021,90.0,72.0,146.0,96.0,131.0,102.0,155.0,124.0,166.0,144.0,77.0,84.0,7.0,16.0,0.0,0.0,0.0,0.0,1410.0
102,25,2022,79.0,68.0,141.0,102.0,136.0,97.0,159.0,119.0,172.0,149.0,91.0,93.0,7.0,30.0,0.0,0.0,0.0,0.0,1443.0
103,25,2023,90.0,62.0,113.0,89.0,129.0,98.0,159.0,128.0,173.0,136.0,109.0,116.0,0.0,30.0,0.0,0.0,0.0,0.0,1432.0
104,26,2020,71.0,88.0,131.0,56.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,363.0
105,26,2021,52.0,71.0,128.0,58.0,14.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,329.0
106,26,2022,46.0,68.0,117.0,53.0,18.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,309.0
107,26,2023,38.0,52.0,112.0,59.0,19.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,288.0
111,27,2023,16.0,11.0,37.0,20.0,30.0,23.0,54.0,32.0,94.0,44.0,42.0,24.0,9.0,16.0,0.0,6.0,0.0,0.0,458.0
115,28,2023,16.0,11.0,37.0,20.0,30.0,23.0,54.0,32.0,94.0,44.0,42.0,24.0,9.0,16.0,0.0,6.0,0.0,0.0,458.0
119,29,2023,51.0,46.0,127.0,58.0,28.0,11.0,6.0,8.0,11.0,6.0,19.0,17.0,0.0,10.0,0.0,0.0,0.0,0.0,398.0
120,30,2020,112.0,95.0,317.0,157.0,191.0,105.0,120.0,88.0,88.0,74.0,30.0,30.0,0.0,18.0,0.0,0.0,0.0,0.0,1425.0
121,30,2021,104.0,81.0,301.0,153.0,210.0,114.0,125.0,82.0,104.0,72.0,38.0,30.0,0.0,6.0,0.0,0.0,0.0,0.0,1420.0
122,30,2022,75.0,68.0,286.0,152.0,207.0,86.0,122.0,89.0,104.0,75.0,38.0,36.0,0.0,13.0,0.0,0.0,0.0,0.0,1351.0
123,30,2023,79.0,92.0,310.0,185.0,275.0,119.0,164.0,105.0,138.0,100.0,53.0,43.0,0.0,7.0,0.0,0.0,0.0,0.0,1670.0
124,31,2020,73.0,69.0,201.0,146.0,143.0,77.0,94.0,91.0,78.0,62.0,38.0,30.0,0.0,6.0,0.0,0.0,0.0,0.0,1108.0
125,31,2021,79.0,90.0,222.0,137.0,143.0,96.0,101.0,99.0,85.0,64.0,28.0,44.0,0.0,14.0,0.0,0.0,0.0,0.0,1202.0
126,31,2022,81.0,66.0,228.0,131.0,153.0,107.0,94.0,87.0,84.0,76.0,29.0,52.0,0.0,8.0,0.0,0.0,0.0,0.0,1196.0
127,31,2023,57.0,59.0,201.0,104.0,153.0,105.0,101.0,84.0,80.0,75.0,24.0,54.0,10.0,26.0,0.0,0.0,0.0,0.0,1133.0
128,32,2020,67.0,78.0,99.0,98.0,167.0,140.0,118.0,110.0,71.0,96.0,7.0,50.0,6.0,21.0,0.0,0.0,0.0,0.0,1128.0
129,32,2021,65.0,65.0,88.0,92.0,167.0,126.0,120.0,110.0,79.0,95.0,12.0,50.0,0.0,31.0,0.0,0.0,0.0,0.0,1100.0
130,32,2022,51.0,56.0,81.0,94.0,150.0,128.0,134.0,105.0,87.0,104.0,14.0,61.0,0.0,35.0,0.0,0.0,0.0,0.0,1100.0
131,32,2023,50.0,51.0,69.0,87.0,142.0,117.0,132.0,99.0,94.0,108.0,32.0,64.0,0.0,40.0,0.0,0.0,0.0,0.0,1085.0
132,33,2020,125.0,124.0,164.0,158.0,236.0,201.0,163.0,162.0,111.0,143.0,57.0,83.0,6.0,34.0,0.0,0.0,0.0,0.0,1767.0
133,33,2021,126.0,108.0,145.0,141.0,211.0,182.0,158.0,164.0,117.0,149.0,60.0,83.0,7.0,46.0,0.0,0.0,0.0,0.0,1697.0
134,33,2022,133.0,105.0,129.0,142.0,206.0,182.0,168.0,164.0,120.0,167.0,66.0,85.0,14.0,35.0,0.0,0.0,0.0,0.0,1716.0
135,33,2023,112.0,108.0,120.0,121.0,197.0,187.0,160.0,172.0,122.0,156.0,72.0,92.0,16.0,43.0,0.0,0.0,0.0,0.0,1678.0

In [ ]:
def year(df):
    # 'pop'으로 끝나는 열만 추출
    pop_cols = [col for col in df.columns if col.endswith('pop')]

    # 필드값(field_1)과 연도(year)별 합계 계산
    grouped = df.groupby(['field_1', 'year'])[pop_cols].sum()
    grouped['pop_total'] = grouped.sum(axis=1)-grouped['total_pop'] # 모든 pop 값의 합계

    # 연도별 pop_total 값을 열로 변환
    averages = grouped['pop_total'].unstack(level=1).reset_index()
    averages.columns = ['field_1'] + [f'{year}총합' for year in averages.columns[1:]]

    # 최종 데이터프레임 생성
    final_result = df[['field_1']].drop_duplicates().merge(averages, on='field_1', how='outer')

    return final_result

# 예제 사용
HS_연총합 = year(HS_공유차량_거주인구)
HN_연총합 = year(HN_공유차량_거주인구)

In [ ]:
HS_연총합

    field_1  2020총합  2021총합  2022총합  2023총합
0         0   962.0  1020.0   976.0   965.0
1         1  1029.0  1058.0  1055.0   962.0
2         2   789.0   828.0   789.0   510.0
3         3  1666.0  1672.0  1690.0  1596.0
4         4   754.0   746.0   746.0   733.0
5         5  1573.0  1579.0  1587.0  1556.0
6         6  1012.0  1060.0  1053.0   876.0
7         7  1688.0  1759.0  1763.0  1765.0
8         8   356.0   392.0   388.0   618.0
9         9   847.0   851.0   870.0   875.0
10       10  1229.0  1400.0  1397.0  1390.0
11       11   376.0   395.0   415.0   383.0
12       12   801.0   812.0   821.0   768.0
13       13     NaN     NaN     NaN  1448.0
14       14     NaN     NaN     NaN  1448.0
15       15   814.0  1425.0  1459.0  1294.0
16       16     8.0  1443.0  1642.0  1615.0
17       17     8.0  1443.0  1642.0  1615.0
18       18   483.0   657.0   642.0   676.0
19       19  1832.0  1961.0  2040.0  2024.0
20       20  1832.0  1961.0  2040.0  2024.0
21       21  3146.0  3160.0  3197.0  3028.0
22       22  1032.0  1006.0  1025.0   970.0
23       23   205.0   310.0   314.0   313.0
24       24   596.0   607.0   642.0   599.0
25       25  1437.0  1410.0  1443.0  1432.0
26       26   363.0   329.0   309.0   288.0
27       27     NaN     NaN     NaN   458.0
28       28     NaN     NaN     NaN   458.0
29       29     NaN     NaN     NaN   398.0
30       30  1425.0  1420.0  1351.0  1670.0
31       31  1108.0  1202.0  1196.0  1133.0
32       32  1128.0  1100.0  1100.0  1085.0
33       33  1767.0  1697.0  1716.0  1678.0

In [ ]:
def aggregate_population_field(df):
    # 'pop'으로 끝나는 컬럼 선택
    pop_columns = [col for col in df.columns if col.endswith('pop')]
    aggregated = df.groupby('field_1')[pop_columns].mean().reset_index()

    return aggregated

HS_공유차량_거주인구= aggregate_population_field(HS_공유차량_거주인구)
HN_공유차량_거주인구= aggregate_population_field(HN_공유차량_거주인구)

In [ ]:
def calculate(pop_gdf):
    pop_cols = [col for col in pop_gdf.columns if 'pop' in col]

    total_pop = pop_gdf[pop_cols].sum(axis=1)-pop_gdf['total_pop']
    male_pop = pop_gdf[[col for col in pop_cols if col.startswith('m')]].sum(axis=1)
    female_pop = pop_gdf[[col for col in pop_cols if col.startswith('w')]].sum(axis=1)
    drivable_cols = [col for col in pop_cols if any(age in col for age in ['20g', '30g', '40g', '50g', '60g', '70g'])]
    high_risk_cols = [col for col in pop_cols if any(age in col for age in ['80g', '90g', '100g'])]

    drivable_pop = pop_gdf[drivable_cols].sum(axis=1)
    high_risk_pop = pop_gdf[high_risk_cols].sum(axis=1)

    calculated_df = pd.DataFrame({
        'field_1' : pop_gdf['field_1'],
        '년 평균 total': total_pop,
        'male': male_pop,
        'female': female_pop,
        'drivable': drivable_pop,
        'high_risk': high_risk_pop
    })

    return calculated_df

HS_공유차량_거주인구= calculate(HS_공유차량_거주인구)
HN_공유차량_거주인구= calculate(HN_공유차량_거주인구)

In [ ]:
HS_공유차량_거주인구

    field_1  년 평균 total     male   female  drivable  high_risk
0         0      980.75   590.50   390.25    964.75      16.00
1         1     1026.00   524.50   501.50    992.50      33.50
2         2      729.00   406.00   323.00    715.50      13.50
3         3     1656.00   722.75   933.25   1563.50      92.50
4         4      744.75   444.50   300.25    744.75       0.00
5         5     1573.75   790.25   783.50   1571.75       2.00
6         6     1000.25   493.50   506.75    998.75       1.50
7         7     1743.75   871.00   872.75   1743.75       0.00
8         8      438.50   200.25   238.25    438.50       0.00
9         9      860.75   425.00   435.75    860.75       0.00
10       10     1354.00   677.25   676.75   1354.00       0.00
11       11      392.25   233.75   158.50    392.25       0.00
12       12      800.50   390.75   409.75    771.25      29.25
13       13     1448.00   620.00   828.00   1395.00      53.00
14       14     1448.00   620.00   828.00   1395.00      53.00
15       15     1248.00   636.50   611.50   1234.50      13.50
16       16     1177.00   610.00   567.00   1159.25      17.75
17       17     1177.00   610.00   567.00   1159.25      17.75
18       18      614.50   354.75   259.75    610.50       4.00
19       19     1964.25   930.75  1033.50   1844.50     119.75
20       20     1964.25   930.75  1033.50   1844.50     119.75
21       21     3132.75  1385.75  1747.00   2982.75     150.00
22       22     1008.25   475.00   533.25    960.25      48.00
23       23      285.50   211.50    74.00    285.50       0.00
24       24      611.00   322.25   288.75    594.25      16.75
25       25     1430.50   775.00   655.50   1403.00      27.50
26       26      322.25   190.75   131.50    322.25       0.00
27       27      458.00   282.00   176.00    427.00      31.00
28       28      458.00   282.00   176.00    427.00      31.00
29       29      398.00   242.00   156.00    388.00      10.00
30       30     1466.50   897.75   568.75   1455.50      11.00
31       31     1159.75   645.00   514.75   1143.75      16.00
32       32     1103.25   525.50   577.75   1070.00      33.25
33       33     1714.50   830.25   884.25   1664.25      50.25

In [ ]:
def outer_join(df1, df2):
    # field_1을 기준으로 아우터 조인
    merged_df = pd.merge(df1, df2, on='field_1', how='outer')
    return merged_df

HS_공유차량_거주인구=outer_join(HS_연총합,HS_공유차량_거주인구)
HN_공유차량_거주인구=outer_join(HN_연총합,HN_공유차량_거주인구)

In [ ]:
HS_공유차량_거주인구.fillna(0, inplace=True)
HN_공유차량_거주인구.fillna(0, inplace=True)

In [ ]:
HS_공유차량_거주인구

,field_1,2020총합,2021총합,2022총합,2023총합,년 평균 total,male,female,drivable,high_risk
0,0,962.0,1020.0,976.0,965.0,980.75,590.50,390.25,964.75,16.00
1,1,1029.0,1058.0,1055.0,962.0,1026.00,524.50,501.50,992.50,33.50
2,2,789.0,828.0,789.0,510.0,729.00,406.00,323.00,715.50,13.50
3,3,1666.0,1672.0,1690.0,1596.0,1656.00,722.75,933.25,1563.50,92.50
4,4,754.0,746.0,746.0,733.0,744.75,444.50,300.25,744.75,0.00
5,5,1573.0,1579.0,1587.0,1556.0,1573.75,790.25,783.50,1571.75,2.00
6,6,1012.0,1060.0,1053.0,876.0,1000.25,493.50,506.75,998.75,1.50
7,7,1688.0,1759.0,1763.0,1765.0,1743.75,871.00,872.75,1743.75,0.00
8,8,356.0,392.0,388.0,618.0,438.50,200.25,238.25,438.50,0.00
9,9,847.0,851.0,870.0,875.0,860.75,425.00,435.75,860.75,0.00
10,10,1229.0,1400.0,1397.0,1390.0,1354.00,677.25,676.75,1354.00,0.00
11,11,376.0,395.0,415.0,383.0,392.25,233.75,158.50,392.25,0.00
12,12,801.0,812.0,821.0,768.0,800.50,390.75,409.75,771.25,29.25
13,13,0.0,0.0,0.0,1448.0,1448.00,620.00,828.00,1395.00,53.00
14,14,0.0,0.0,0.0,1448.0,1448.00,620.00,828.00,1395.00,53.00
15,15,814.0,1425.0,1459.0,1294.0,1248.00,636.50,611.50,1234.50,13.50
16,16,8.0,1443.0,1642.0,1615.0,1177.00,610.00,567.00,1159.25,17.75
17,17,8.0,1443.0,1642.0,1615.0,1177.00,610.00,567.00,1159.25,17.75
18,18,483.0,657.0,642.0,676.0,614.50,354.75,259.75,610.50,4.00
19,19,1832.0,1961.0,2040.0,2024.0,1964.25,930.75,1033.50,1844.50,119.75
20,20,1832.0,1961.0,2040.0,2024.0,1964.25,930.75,1033.50,1844.50,119.75
21,21,3146.0,3160.0,3197.0,3028.0,3132.75,1385.75,1747.00,2982.75,150.00
22,22,1032.0,1006.0,1025.0,970.0,1008.25,475.00,533.25,960.25,48.00
23,23,205.0,310.0,314.0,313.0,285.50,211.50,74.00,285.50,0.00
24,24,596.0,607.0,642.0,599.0,611.00,322.25,288.75,594.25,16.75
25,25,1437.0,1410.0,1443.0,1432.0,1430.50,775.00,655.50,1403.00,27.50
26,26,363.0,329.0,309.0,288.0,322.25,190.75,131.50,322.25,0.00
27,27,0.0,0.0,0.0,458.0,458.00,282.00,176.00,427.00,31.00
28,28,0.0,0.0,0.0,458.0,458.00,282.00,176.00,427.00,31.00
29,29,0.0,0.0,0.0,398.0,398.00,242.00,156.00,388.00,10.00
30,30,1425.0,1420.0,1351.0,1670.0,1466.50,897.75,568.75,1455.50,11.00
31,31,1108.0,1202.0,1196.0,1133.0,1159.75,645.00,514.75,1143.75,16.00
32,32,1128.0,1100.0,1100.0,1085.0,1103.25,525.50,577.75,1070.00,33.25
33,33,1767.0,1697.0,1716.0,1678.0,1714.50,830.25,884.25,1664.25,50.25

In [ ]:
HN_공유차량_거주인구['총합']=HN_공유차량_거주인구['2020총합']+HN_공유차량_거주인구['2021총합']+HN_공유차량_거주인구['2022총합']+HN_공유차량_거주인구['2023총합']
HS_공유차량_거주인구['총합']=HS_공유차량_거주인구['2020총합']+HS_공유차량_거주인구['2021총합']+HS_공유차량_거주인구['2022총합']+HS_공유차량_거주인구['2023총합']

In [ ]:
def merge_public_population(public_df,population_df):
    # HS_공공의 첫 번째 열 이름 확인
    public_key = public_df.columns[0]

    # 병합 수행
    merged_df = pd.merge(
        public_df,
        population_df,
        left_on=public_key,
        right_on='field_1',
        how='left'
    )

    return merged_df


# 병합 실행
HS_공공= merge_public_population(HS_공공, HS_공유차량_거주인구)
HS_국민 =merge_public_population(HS_국민, HS_공유차량_거주인구)
HS_영구 = merge_public_population(HS_영구, HS_공유차량_거주인구)
HS_행복 = merge_public_population(HS_행복, HS_공유차량_거주인구)
HN_공공 = merge_public_population(HN_공공, HN_공유차량_거주인구)
HN_국민 = merge_public_population(HN_국민, HN_공유차량_거주인구)
HN_행복 = merge_public_population(HN_행복, HN_공유차량_거주인구)
HN_영구 = merge_public_population(HN_영구, HN_공유차량_거주인구)

In [ ]:
HS_공공

,Unnamed: 0,blck_cd,cnt_2008,tm_2008,cnt_2009,tm_2009,cnt_2010,tm_2010,cnt_2011,tm_2011,cnt_2012,tm_2012,cnt_2101,tm_2101,cnt_2102,tm_2102,cnt_2103,tm_2103,cnt_2104,tm_2104,cnt_2105,tm_2105,cnt_2106,tm_2106,cnt_2107,tm_2107,cnt_2108,tm_2108,cnt_2109,tm_2109,cnt_2110,tm_2110,cnt_2111,tm_2111,cnt_2112,tm_2112,cnt_2201,tm_2201,cnt_2202,tm_2202,cnt_2203,tm_2203,cnt_2204,tm_2204,cnt_2205,tm_2205,cnt_2206,tm_2206,cnt_2207,tm_2207,cnt_2208,tm_2208,cnt_2209,tm_2209,cnt_2210,tm_2210,cnt_2211,tm_2211,cnt_2212,tm_2212,cnt_2301,tm_2301,cnt_2302,tm_2302,cnt_2303,tm_2303,cnt_2304,tm_2304,cnt_2305,tm_2305,cnt_2306,tm_2306,cnt_2307,tm_2307,cnt_2308,tm_2308,cnt_2309,tm_2309,cnt_2310,tm_2310,cnt_2311,tm_2311,cnt_2312,tm_2312,total_cnt,total_tm,car_type,car_cnt,month,m_cnt,m_tm,type,noh,parking_slot,lon,lat,geometry,field_1,2020총합,2021총합,2022총합,2023총합,년 평균 total,male,female,drivable,high_risk,총합
0,5,C01890,13.0,26.0,19.0,44.0,22.0,122.0,14,41,18,36,19,46,28,69,22,52,21,50,20,118,38,151,30,129,58,92,35,96,43,150,49,131,37,66,31,76,27,64,26,79,30,62,24,58,18,60,30,130,21,45,18,84,14,49,18,58,22,60,15,34,18,44,25,44,26,57,20,24,18,36,19,48,12,27,11,9,8,21,4,3,0,0,937,2590,올뉴모닝,1,41.0,22.853659,63.170732,공공임대,754,1131.0,127.103636,37.176328,POINT (127.10364 37.17633),5,1573.0,1579.0,1587.0,1556.0,1573.75,790.25,783.50,1571.75,2.0,6295.0
1,6,C02014,31.0,125.0,25.0,85.0,39.0,119.0,36,102,36,73,34,96,32,112,46,113,48,155,34,184,47,123,36,145,40,116,34,171,45,150,48,132,44,125,35,180,50,142,33,111,35,149,37,187,42,196,51,190,43,305,42,216,41,138,42,102,27,53,35,116,29,55,42,73,38,105,32,119,26,56,39,44,34,126,38,97,27,37,30,35,13,16,1486,4975,올뉴K3,1,41.0,36.243902,121.341463,공공임대,876,1314.0,127.126406,37.183691,POINT (127.12641 37.18369),6,1012.0,1060.0,1053.0,876.0,1000.25,493.50,506.75,998.75,1.5,4001.0
2,7,C02015,26.0,165.0,31.0,90.0,24.0,91.0,29,138,31,75,27,129,21,62,29,90,40,118,54,126,56,137,78,140,45,99,43,171,55,139,55,161,64,154,47,135,52,133,37,99,34,91,41,99,31,117,43,99,29,76,32,112,36,62,40,75,37,126,43,82,34,87,59,65,51,108,47,79,29,29,24,46,30,32,36,48,30,35,17,28,31,62,1581,4013,더뉴레이,1,41.0,38.560976,97.878049,공공임대,882,1323.0,127.118188,37.173069,POINT (127.11819 37.17307),7,1688.0,1759.0,1763.0,1765.0,1743.75,871.00,872.75,1743.75,0.0,6975.0
3,8,C02329,NaN,NaN,NaN,NaN,NaN,NaN,5,16,22,54,24,78,25,86,28,95,19,76,25,80,21,68,30,79,32,80,42,103,43,242,39,123,37,124,41,109,24,55,20,43,30,100,22,63,22,67,23,96,28,115,27,87,26,106,46,153,49,154,50,203,47,116,36,63,57,110,64,102,55,89,65,136,71,94,51,68,36,50,49,78,44,108,1326,3669,더뉴레이,1,38.0,34.894737,96.552632,공공임대,740,1110.0,127.123518,37.175706,POINT (127.12352 37.17571),8,356.0,392.0,388.0,618.0,438.50,200.25,238.25,438.50,0.0,1754.0
4,9,C02160,22.0,72.0,23.0,92.0,28.0,90.0,30,96,34,107,38,128,28,112,45,144,38,127,30,105,37,90,23,92,32,104,35,90,23,86,37,128,30,162,30,83,24,79,36,113,28,84,23,117,34,223,46,215,36,240,35,202,19,130,25,109,33,142,19,109,20,72,33,127,46,153,72,117,51,81,33,40,2,0,25,71,24,45,18,42,16,91,1243,4510,더뉴레이,1,41.0,30.317073,110.000000,공공임대,924,1386.0,127.127443,37.186354,POINT (127.12744 37.18635),9,847.0,851.0,870.0,875.0,860.75,425.00,435.75,860.75,0.0,3443.0
5,10,C02246,23.0,55.0,38.0,90.0,26.0,79.0,46,61,46,83,46,77,38,91,52,93,49,95,26,106,28,58,28,80,28,66,19,170,27,85,35,101,18,45,23,96,33,99,26,55,27,72,35,115,28,104,16,60,26,90,26,86,29,116,31,92,33,95,25,97,26,98,59,86,32,107,27,72,40,58,47,104,32,105,20,103,16,32,30,48,26,39,1256,3463,더뉴레이,1,41.0,30.634146,84.463415,공공임대,856,1284.0,127.094051,37.161979,POINT (127.09405 37.16198),10,1229.0,1400.0,1397.0,1390.0,1354.00,677.25,676.75,1354.00,0.0,5416.0

In [ ]:
def remove(df, prefixes):
    # 접두사에 해당하는 열 찾기
    cols_to_drop = [col for col in df.columns if any(col.startswith(prefix) for prefix in prefixes)]
    # 열 삭제
    df_cleaned = df.drop(columns=cols_to_drop)
    return df_cleaned

# 사용 예시
prefixes= ['cnt', 'tm','field_1']
HN_영구 = remove(HN_영구, prefixes)
HN_공공 = remove(HN_공공, prefixes)
HN_행복 = remove(HN_행복, prefixes)
HN_국민 = remove(HN_국민, prefixes)
HS_영구 = remove(HS_영구, prefixes)
HS_공공 = remove(HS_공공, prefixes)
HS_행복 = remove(HS_행복, prefixes)
HS_국민 = remove(HS_국민, prefixes)

In [ ]:
HN_영구

,Unnamed: 0,blck_cd,total_cnt,total_tm,car_type,car_cnt,month,m_cnt,m_tm,type,noh,parking_slot,lon,lat,geometry,2020총합,2021총합,2022총합,2023총합,년 평균 total,male,female,drivable,high_risk,총합
0,4,C02408,1974,7810,더뉴레이/올뉴모닝/올뉴K3,3.0,35.0,56.400000,223.142857,영구임대,475,712.5,127.163453,37.511638,POINT (127.16345 37.51164),685.0,1245.0,1276.0,1160.0,1091.50,576.75,514.75,1003.0,88.50,4366.0
1,11,C01921,730,2349,모닝어반,1.0,41.0,17.804878,57.292683,영구임대,1152,1728.0,127.188696,37.568623,POINT (127.1887 37.56862),2858.0,2830.0,2822.0,2777.0,2821.75,1367.25,1454.50,2579.0,242.75,11287.0

# 임대료 -> 평수, 임대료

In [ ]:
import geopandas as gpd
from shapely.geometry import Point, box

## 임대료 데이터 처리
HS_공공주택_임대료 = Lon_Lat(HS_공공주택_임대료)
HN_공공주택_임대료 = Lon_Lat(HN_공공주택_임대료)

# 3. 임대료(pay_rent): 평균 계산 함수
def calculate_average_rent_within_buffer(gdf, payment_gdf, buffer_size):
    # 각 점의 버퍼 박스 계산
    minx = gdf['geometry'].x - buffer_size
    miny = gdf['geometry'].y - buffer_size
    maxx = gdf['geometry'].x + buffer_size
    maxy = gdf['geometry'].y + buffer_size

    # 각 점의 버퍼 박스를 GeoDataFrame으로 생성
    buffer_boxes = [box(x1, y1, x2, y2) for x1, y1, x2, y2 in zip(minx, miny, maxx, maxy)]
    buffer_gdf = gpd.GeoDataFrame(geometry=buffer_boxes)

    # 각 버퍼에 포함된 임대료 데이터를 확인
    avg_rents = []
    for buffer_box in buffer_gdf['geometry']:
        # 해당 버퍼에 포함된 데이터 필터링
        within_i = payment_gdf[payment_gdf.within(buffer_box)]

        # 임대료 평균 계산
        avg_rent = within_i['pay_rent'].mean() if not within_i.empty else 0
        avg_rents.append(avg_rent)

    return avg_rents

# 4. 데이터 처리: 데이터프레임에 새로운 열 추가
buffer_size = 0.01  # 버퍼 크기 설정

# 임대료(pay_rent) 평균값 계산
HS_공공['avg_rent'] = calculate_average_rent_within_buffer(HS_공공, HS_공공주택_임대료, buffer_size)
HS_행복['avg_rent'] = calculate_average_rent_within_buffer(HS_행복, HS_공공주택_임대료, buffer_size)
HS_영구['avg_rent'] = calculate_average_rent_within_buffer(HS_영구, HS_공공주택_임대료, buffer_size)
HS_국민['avg_rent'] = calculate_average_rent_within_buffer(HS_국민, HS_공공주택_임대료, buffer_size)

HN_공공['avg_rent'] = calculate_average_rent_within_buffer(HN_공공, HN_공공주택_임대료, buffer_size)
HN_행복['avg_rent'] = calculate_average_rent_within_buffer(HN_행복, HN_공공주택_임대료, buffer_size)
HN_영구['avg_rent'] = calculate_average_rent_within_buffer(HN_영구, HN_공공주택_임대료, buffer_size)
HN_국민['avg_rent'] = calculate_average_rent_within_buffer(HN_국민, HN_공공주택_임대료, buffer_size)

In [ ]:
def calculate_all_pyng_frequencies_multilevel(gdf, payment_gdf, buffer_size=0.01):

    # 각 점의 버퍼 계산
    minx = gdf['geometry'].x - buffer_size
    miny = gdf['geometry'].y - buffer_size
    maxx = gdf['geometry'].x + buffer_size
    maxy = gdf['geometry'].y + buffer_size

    # 버퍼 박스 생성
    buffer_boxes = [box(x1, y1, x2, y2) for x1, y1, x2, y2 in zip(minx, miny, maxx, maxy)]
    buffer_gdf = gpd.GeoDataFrame(geometry=buffer_boxes, index=gdf.index)

    # 빈도 데이터를 저장할 리스트
    frequency_data = []

    # 각 버퍼 내의 데이터 필터링 및 빈도 계산
    for buffer_box in buffer_gdf['geometry']:
        # 버퍼 내 데이터 추출
        within_i = payment_gdf[payment_gdf.within(buffer_box)]

        # 빈도 계산
        if not within_i.empty:
            freq_counts = within_i['pyng'].value_counts().to_dict()
        else:
            freq_counts = {category: 0 for category in payment_gdf['pyng'].unique()}

        frequency_data.append(freq_counts)

    # 빈도 데이터를 정리하여 DataFrame 생성
    categories = sorted(payment_gdf['pyng'].unique())
    frequency_df = pd.DataFrame(frequency_data, index=gdf.index).fillna(0)

    # 멀티 인덱스 설정
    frequency_df = frequency_df.reindex(columns=categories, fill_value=0).astype(int)
    columns = pd.MultiIndex.from_tuples(
        [("평", category) for category in categories],
        names=["상위 인덱스", "구분"]
    )
    frequency_df.columns = columns

    return frequency_df

def merge_with_multilevel_columns(base_df, frequency_df):
    """
    멀티컬럼을 가진 frequency_df를 base_df와 병합.
    """
    base_df = pd.concat([base_df, frequency_df], axis=1)
    base_df.columns = pd.MultiIndex.from_tuples(
        [(col[0], col[1]) if isinstance(col, tuple) else (col, '') for col in base_df.columns],
        names=["상위 인덱스", "구분"]
    )
    return base_df

# 멀티컬럼 유지 병합
공공_df = calculate_all_pyng_frequencies_multilevel(HS_공공, HS_공공주택_임대료, buffer_size)
HS_공공 = merge_with_multilevel_columns(HS_공공, 공공_df)

영구_df = calculate_all_pyng_frequencies_multilevel(HS_영구, HS_공공주택_임대료, buffer_size)
HS_영구 = merge_with_multilevel_columns(HS_영구, 영구_df)

행복_df = calculate_all_pyng_frequencies_multilevel(HS_행복, HS_공공주택_임대료, buffer_size)
HS_행복 = merge_with_multilevel_columns(HS_행복, 행복_df)

국민_df = calculate_all_pyng_frequencies_multilevel(HS_국민, HS_공공주택_임대료, buffer_size)
HS_국민 = merge_with_multilevel_columns(HS_국민, 국민_df)

공공_df = calculate_all_pyng_frequencies_multilevel(HN_공공, HN_공공주택_임대료, buffer_size)
HN_공공 = merge_with_multilevel_columns(HN_공공, 공공_df)

영구_df = calculate_all_pyng_frequencies_multilevel(HN_영구, HN_공공주택_임대료, buffer_size)
HN_영구 = merge_with_multilevel_columns(HN_영구, 영구_df)

행복_df = calculate_all_pyng_frequencies_multilevel(HN_행복, HN_공공주택_임대료, buffer_size)
HN_행복 = merge_with_multilevel_columns(HN_행복, 행복_df)

국민_df = calculate_all_pyng_frequencies_multilevel(HN_국민, HN_공공주택_임대료, buffer_size)
HN_국민 = merge_with_multilevel_columns(HN_국민, 국민_df)

In [ ]:
HN_공공

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm   car_type car_cnt month  \
구분
0               0  C02258      2274     5653  모닝어반/올뉴K3     2.0  40.0
1               1  C02256       879     3066       더뉴레이     1.0  35.0
2               5  C02352       989     3947       더뉴레이     1.0  31.0
3               6  C02012      1968     6490  모닝어반/올뉴K3     2.0  41.0
4               7  C02126       620     2116       더뉴레이     1.0  41.0
5               8  C02127      1062     1916       더뉴레이     1.0  38.0
6               9  C01967       935     1868        NaN     NaN  37.0
7              10  C01801       124      482        NaN     NaN  27.0

상위 인덱스      m_cnt        m_tm  type   noh parking_slot         lon        lat  \
구분
0       56.850000  141.325000  공공임대   669       1003.5  127.150707  37.506900
1       25.114286   87.600000  공공임대   753       1129.5  127.161716  37.508457
2       31.903226  127.322581  공공임대   617        925.5  127.162026  37.512136
3       48.000000  158.292683  공공임대   988       1482.0  127.180686  37.572709
4       15.121951   51.609756  공공임대   871       1306.5  127.192715  37.559570
5       27.947368   50.421053  공공임대   688       1032.0  127.192498  37.557710
6       25.270270   50.486486  공공임대  1193       1789.5  127.198429  37.561666
7        4.592593   17.851852  공공임대    38         57.0  127.188448  37.570743

상위 인덱스                    geometry  2020총합  2021총합  2022총합  2023총합 년 평균 total  \
구분
0        POINT (127.15071 37.5069)  1302.0  1302.0  1289.0  1315.0    1302.00
1       POINT (127.16172 37.50846)  1611.0  1625.0  1606.0  1597.0    1609.75
2       POINT (127.16203 37.51214)   142.0  1365.0  1367.0  1209.0    1020.75
3       POINT (127.18069 37.57271)  2203.0  2195.0  2200.0  2178.0    2194.00
4       POINT (127.19271 37.55957)  1339.0  1347.0  1346.0  1655.0    1421.75
5        POINT (127.1925 37.55771)  1601.0  1597.0  1588.0  1592.0    1594.50
6       POINT (127.19843 37.56167)  2595.0  2616.0  2621.0  2614.0    2611.50
7       POINT (127.18845 37.57074)  1223.0  1188.0  1200.0  1194.0    1201.25

상위 인덱스     male   female drivable high_risk       총합       avg_rent      평  \
구분                                                                  10평 이하
0        629.00   673.00  1287.25     14.75   5208.0  301666.666667      2
1        794.50   815.25  1603.25      6.50   6439.0  318181.818182      4
2        508.25   512.50   994.25     26.50   4083.0  318181.818182      4
3       1094.00  1100.00  2185.25      8.75   8776.0  288000.000000      4
4        709.50   712.25  1408.50     13.25   5687.0  395833.333333      3
5        779.25   815.25  1589.75      4.75   6378.0  468888.888889      1
6       1284.75  1326.75  2569.75     41.75  10446.0  367142.857143      4
7        618.75   582.50  1172.00     29.25   4805.0  314000.000000      5

상위 인덱스
구분     20평 이하 30평 이하
0           3      1
1           5      2
2           5      2
3           4      2
4           6      3
5           5      3
6           6      4
7           7      3

# 단지별 공유차량 건당 평균 사용 시간

In [ ]:
def m (df):
  df['건당 평균 사용 시간']=df['m_tm']/df['m_cnt']
  return df

In [ ]:
m(HN_공공 )
m(HN_영구)
m(HN_행복)
m(HN_국민)
m(HS_공공)
m(HS_영구)
m(HS_행복)
m(HS_국민)

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm   car_type car_cnt month  \
구분
0               0  C02347       855     2888       모닝어반     1.0  41.0
1               1  C01961       104      645        NaN     NaN  16.0
2               2  C02042       889     2151        NaN     NaN  37.0
3               3  C01569      1377     3912       더뉴레이     1.0  41.0
4              12  C02194       565     2977        NaN     NaN  37.0
5              13  C02512       426     1241       올뉴K3     1.0  19.0
6              17  C02413       637     2260        NaN     NaN  31.0
7              19  C01873      2142     6802  모닝어반/올뉴K3     2.0  41.0
8              21  C01571      1630     5639  더뉴레이/올뉴K3     2.0  41.0
9              22  C01574       925     3028        NaN     NaN  37.0
10             24  C02140      1324     5001        NaN     NaN  37.0
11             25  C02139      1653     5815       올뉴모닝     1.0  41.0
12             27  C02562         6       57        NaN     NaN   4.0
13             30  C02049       501     1770        NaN     NaN  27.0
14             31  C01973       510     1587        NaN     NaN  34.0
15             32  C01588       148      879        NaN     NaN  25.0
16             33  C01589       195     1027        NaN     NaN  30.0

상위 인덱스      m_cnt        m_tm  type   noh parking_slot         lon        lat  \
구분
0       20.853659   70.439024  국민임대  1022       1533.0  126.834651  37.206978
1        6.500000   40.312500  국민임대   876       1314.0  126.829787  37.210028
2       24.027027   58.135135  국민임대   782       1173.0  126.833895  37.209028
3       33.585366   95.414634  국민임대   963       1444.5  127.061128  37.211268
4       15.270270   80.459459  국민임대   730       1095.0  127.115160  37.217529
5       22.421053   65.315789  국민임대  1031       1546.5  127.105712  37.211973
6       20.548387   72.903226  국민임대  1230       1845.0  127.121299  37.164322
7       52.243902  165.902439  국민임대  1547       2320.5  127.121597  37.206009
8       39.756098  137.536585  국민임대  2342       3513.0  127.069179  37.193522
9       25.000000   81.837838  국민임대   915       1372.5  126.960738  37.218666
10      35.783784  135.162162  국민임대  1028       1542.0  126.943852  37.221747
11      40.317073  141.829268  국민임대   972       1458.0  126.952162  37.225114
12       1.500000   14.250000  국민임대   449        673.5  126.876172  37.244215
13      18.555556   65.555556  국민임대  1742       2613.0  126.896338  37.097377
14      15.000000   46.676471  국민임대  1242       1863.0  126.906221  37.115500
15       5.920000   35.160000  국민임대  1150       1725.0  126.915635  37.124382
16       6.500000   34.233333  국민임대  1330       1995.0  126.918489  37.124146

상위 인덱스                    geometry  2020총합  2021총합  2022총합  2023총합 년 평균 total  \
구분
0       POINT (126.83465 37.20698)   962.0  1020.0   976.0   965.0     980.75
1       POINT (126.82979 37.21003)  1029.0  1058.0  1055.0   962.0    1026.00
2        POINT (126.8339 37.20903)   789.0   828.0   789.0   510.0     729.00
3       POINT (127.06113 37.21127)  1666.0  1672.0  1690.0  1596.0    1656.00
4       POINT (127.11516 37.21753)   801.0   812.0   821.0   768.0     800.50
5       POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0    1448.00
6        POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0    1177.00
7        POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0    1964.25
8       POINT (127.06918 37.19352)  3146.0  3160.0  3197.0  3028.0    3132.75
9       POINT (126.96074 37.21867)  1032.0  1006.0  1025.0   970.0    1008.25
10      POINT (126.94385 37.22175)   596.0   607.0   642.0   599.0     611.00
11      POINT (126.95216 37.22511)  1437.0  1410.0  1443.0  1432.0    1430.50
12      POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0     458.00
13      POINT (126.89634 37.09738)  1425.0  1420.0  1351.0  1670.0    1466.50
14       POINT (126.90622 37.1155)  1108.0  1202.0  1196.0  1133.0    1159.75
15      POINT (126.91564 37.12438)  1128.0  1100.0  1100.0  1085.0    1103.25
16      POINT (126.91849 37.12415)  1767.0  1697.0  1716.0  1678.0    1714.50

상위 인덱스     male   female drivable high_risk       총합       avg_rent      평  \
구분                                                                  10평 이하
0        590.50   390.25   964.75     16.00   3923.0  170000.000000      8
1        524.50   501.50   992.50     33.50   4104.0  196666.666667      4
2        406.00   323.00   715.50     13.50   2916.0  170000.000000      8
3        722.75   933.25  1563.50     92.50   6624.0  242000.000000      0
4        390.75   409.75   771.25     29.25   3202.0  168750.000000      5
5        620.00   828.00  1395.00     53.00   1448.0  168750.000000      5
6        610.00   567.00  1159.25     17.75   4708.0  333750.000000      3
7        930.75  1033.50  1844.50    119.75   7857.0  206666.666667      2
8       1385.75  1747.00  2982.75    150.00  12531.0  365000.000000      0
9        475.00   533.25   960.25     48.00   4033.0  175714.285714      2
10       322.25   288.75   594.25     16.75   2444.0  210000.000000      5
11       775.00   655.50  1403.00     27.50   5722.0  209375.000000      5
12       282.00   176.00   427.00     31.00    458.0  132727.272727      7
13       897.75   568.75  1455.50     11.00   5866.0  180000.000000      1
14       645.00   514.75  1143.75     16.00   4639.0  184444.444444      4
15       525.50   577.75  1070.00     33.25   4413.0  148181.818182      5
16       830.25   884.25  1664.25     50.25   6858.0  136666.666667      4

상위 인덱스               건당 평균 사용 시간
구분     20평 이하 30평 이하
0           7      1    3.377778
1           4      1    6.201923
2           7      1    2.419573
3           5      0    2.840959
4           3      0    5.269027
5           3      0    2.913146
6           3      2    3.547881
7           1      0    3.175537
8           1      1    3.459509
9           5      0    3.273514
10          7      1    3.777190
11         10      1    3.517846
12          4      0    9.500000
13          1      0    3.532934
14          4      1    3.111765
15          6      0    5.939189
16          5      0    5.266667

# 1세대당 평균 공유차량 사용건수/시간

In [ ]:
def noh_m(df):
  df['세대 평균 사용 건수']=df['m_cnt']/df['noh']
  df['세대 평균 사용 시간']=df['m_tm']/df['noh']
  return df

In [ ]:
noh_m(HN_공공)
noh_m(HN_영구)
noh_m(HN_행복)
noh_m(HN_국민)
noh_m(HS_공공)
noh_m(HS_영구)
noh_m(HS_행복)
noh_m(HS_국민)

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm   car_type car_cnt month  \
구분
0               0  C02347       855     2888       모닝어반     1.0  41.0
1               1  C01961       104      645        NaN     NaN  16.0
2               2  C02042       889     2151        NaN     NaN  37.0
3               3  C01569      1377     3912       더뉴레이     1.0  41.0
4              12  C02194       565     2977        NaN     NaN  37.0
5              13  C02512       426     1241       올뉴K3     1.0  19.0
6              17  C02413       637     2260        NaN     NaN  31.0
7              19  C01873      2142     6802  모닝어반/올뉴K3     2.0  41.0
8              21  C01571      1630     5639  더뉴레이/올뉴K3     2.0  41.0
9              22  C01574       925     3028        NaN     NaN  37.0
10             24  C02140      1324     5001        NaN     NaN  37.0
11             25  C02139      1653     5815       올뉴모닝     1.0  41.0
12             27  C02562         6       57        NaN     NaN   4.0
13             30  C02049       501     1770        NaN     NaN  27.0
14             31  C01973       510     1587        NaN     NaN  34.0
15             32  C01588       148      879        NaN     NaN  25.0
16             33  C01589       195     1027        NaN     NaN  30.0

상위 인덱스      m_cnt        m_tm  type   noh parking_slot         lon        lat  \
구분
0       20.853659   70.439024  국민임대  1022       1533.0  126.834651  37.206978
1        6.500000   40.312500  국민임대   876       1314.0  126.829787  37.210028
2       24.027027   58.135135  국민임대   782       1173.0  126.833895  37.209028
3       33.585366   95.414634  국민임대   963       1444.5  127.061128  37.211268
4       15.270270   80.459459  국민임대   730       1095.0  127.115160  37.217529
5       22.421053   65.315789  국민임대  1031       1546.5  127.105712  37.211973
6       20.548387   72.903226  국민임대  1230       1845.0  127.121299  37.164322
7       52.243902  165.902439  국민임대  1547       2320.5  127.121597  37.206009
8       39.756098  137.536585  국민임대  2342       3513.0  127.069179  37.193522
9       25.000000   81.837838  국민임대   915       1372.5  126.960738  37.218666
10      35.783784  135.162162  국민임대  1028       1542.0  126.943852  37.221747
11      40.317073  141.829268  국민임대   972       1458.0  126.952162  37.225114
12       1.500000   14.250000  국민임대   449        673.5  126.876172  37.244215
13      18.555556   65.555556  국민임대  1742       2613.0  126.896338  37.097377
14      15.000000   46.676471  국민임대  1242       1863.0  126.906221  37.115500
15       5.920000   35.160000  국민임대  1150       1725.0  126.915635  37.124382
16       6.500000   34.233333  국민임대  1330       1995.0  126.918489  37.124146

상위 인덱스                    geometry  2020총합  2021총합  2022총합  2023총합 년 평균 total  \
구분
0       POINT (126.83465 37.20698)   962.0  1020.0   976.0   965.0     980.75
1       POINT (126.82979 37.21003)  1029.0  1058.0  1055.0   962.0    1026.00
2        POINT (126.8339 37.20903)   789.0   828.0   789.0   510.0     729.00
3       POINT (127.06113 37.21127)  1666.0  1672.0  1690.0  1596.0    1656.00
4       POINT (127.11516 37.21753)   801.0   812.0   821.0   768.0     800.50
5       POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0    1448.00
6        POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0    1177.00
7        POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0    1964.25
8       POINT (127.06918 37.19352)  3146.0  3160.0  3197.0  3028.0    3132.75
9       POINT (126.96074 37.21867)  1032.0  1006.0  1025.0   970.0    1008.25
10      POINT (126.94385 37.22175)   596.0   607.0   642.0   599.0     611.00
11      POINT (126.95216 37.22511)  1437.0  1410.0  1443.0  1432.0    1430.50
12      POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0     458.00
13      POINT (126.89634 37.09738)  1425.0  1420.0  1351.0  1670.0    1466.50
14       POINT (126.90622 37.1155)  1108.0  1202.0  1196.0  1133.0    1159.75
15      POINT (126.91564 37.12438)  1128.0  1100.0  1100.0  1085.0    1103.25
16      POINT (126.91849 37.12415)  1767.0  1697.0  1716.0  1678.0    1714.50

상위 인덱스     male   female drivable high_risk       총합       avg_rent      평  \
구분                                                                  10평 이하
0        590.50   390.25   964.75     16.00   3923.0  170000.000000      8
1        524.50   501.50   992.50     33.50   4104.0  196666.666667      4
2        406.00   323.00   715.50     13.50   2916.0  170000.000000      8
3        722.75   933.25  1563.50     92.50   6624.0  242000.000000      0
4        390.75   409.75   771.25     29.25   3202.0  168750.000000      5
5        620.00   828.00  1395.00     53.00   1448.0  168750.000000      5
6        610.00   567.00  1159.25     17.75   4708.0  333750.000000      3
7        930.75  1033.50  1844.50    119.75   7857.0  206666.666667      2
8       1385.75  1747.00  2982.75    150.00  12531.0  365000.000000      0
9        475.00   533.25   960.25     48.00   4033.0  175714.285714      2
10       322.25   288.75   594.25     16.75   2444.0  210000.000000      5
11       775.00   655.50  1403.00     27.50   5722.0  209375.000000      5
12       282.00   176.00   427.00     31.00    458.0  132727.272727      7
13       897.75   568.75  1455.50     11.00   5866.0  180000.000000      1
14       645.00   514.75  1143.75     16.00   4639.0  184444.444444      4
15       525.50   577.75  1070.00     33.25   4413.0  148181.818182      5
16       830.25   884.25  1664.25     50.25   6858.0  136666.666667      4

상위 인덱스               건당 평균 사용 시간 세대 평균 사용 건수 세대 평균 사용 시간
구분     20평 이하 30평 이하
0           7      1    3.377778    0.020405    0.068923
1           4      1    6.201923    0.007420    0.046019
2           7      1    2.419573    0.030725    0.074342
3           5      0    2.840959    0.034876    0.099081
4           3      0    5.269027    0.020918    0.110218
5           3      0    2.913146    0.021747    0.063352
6           3      2    3.547881    0.016706    0.059271
7           1      0    3.175537    0.033771    0.107241
8           1      1    3.459509    0.016975    0.058726
9           5      0    3.273514    0.027322    0.089440
10          7      1    3.777190    0.034809    0.131481
11         10      1    3.517846    0.041478    0.145915
12          4      0    9.500000    0.003341    0.031737
13          1      0    3.532934    0.010652    0.037632
14          4      1    3.111765    0.012077    0.037582
15          6      0    5.939189    0.005148    0.030574
16          5      0    5.266667    0.004887    0.025739

# 현재 공유차량 제도 사용 현황(0(없음), 1(있음))

In [ ]:
def now(df):
  df['now'] = df['car_cnt'].notna().astype(int)
  return df

In [ ]:
now(HN_공공)
now(HN_영구)
now(HN_행복)
now(HN_국민)
now(HS_공공)
now(HS_영구)
now(HS_행복)
now(HS_국민)

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm   car_type car_cnt month  \
구분
0               0  C02347       855     2888       모닝어반     1.0  41.0
1               1  C01961       104      645        NaN     NaN  16.0
2               2  C02042       889     2151        NaN     NaN  37.0
3               3  C01569      1377     3912       더뉴레이     1.0  41.0
4              12  C02194       565     2977        NaN     NaN  37.0
5              13  C02512       426     1241       올뉴K3     1.0  19.0
6              17  C02413       637     2260        NaN     NaN  31.0
7              19  C01873      2142     6802  모닝어반/올뉴K3     2.0  41.0
8              21  C01571      1630     5639  더뉴레이/올뉴K3     2.0  41.0
9              22  C01574       925     3028        NaN     NaN  37.0
10             24  C02140      1324     5001        NaN     NaN  37.0
11             25  C02139      1653     5815       올뉴모닝     1.0  41.0
12             27  C02562         6       57        NaN     NaN   4.0
13             30  C02049       501     1770        NaN     NaN  27.0
14             31  C01973       510     1587        NaN     NaN  34.0
15             32  C01588       148      879        NaN     NaN  25.0
16             33  C01589       195     1027        NaN     NaN  30.0

상위 인덱스      m_cnt        m_tm  type   noh parking_slot         lon        lat  \
구분
0       20.853659   70.439024  국민임대  1022       1533.0  126.834651  37.206978
1        6.500000   40.312500  국민임대   876       1314.0  126.829787  37.210028
2       24.027027   58.135135  국민임대   782       1173.0  126.833895  37.209028
3       33.585366   95.414634  국민임대   963       1444.5  127.061128  37.211268
4       15.270270   80.459459  국민임대   730       1095.0  127.115160  37.217529
5       22.421053   65.315789  국민임대  1031       1546.5  127.105712  37.211973
6       20.548387   72.903226  국민임대  1230       1845.0  127.121299  37.164322
7       52.243902  165.902439  국민임대  1547       2320.5  127.121597  37.206009
8       39.756098  137.536585  국민임대  2342       3513.0  127.069179  37.193522
9       25.000000   81.837838  국민임대   915       1372.5  126.960738  37.218666
10      35.783784  135.162162  국민임대  1028       1542.0  126.943852  37.221747
11      40.317073  141.829268  국민임대   972       1458.0  126.952162  37.225114
12       1.500000   14.250000  국민임대   449        673.5  126.876172  37.244215
13      18.555556   65.555556  국민임대  1742       2613.0  126.896338  37.097377
14      15.000000   46.676471  국민임대  1242       1863.0  126.906221  37.115500
15       5.920000   35.160000  국민임대  1150       1725.0  126.915635  37.124382
16       6.500000   34.233333  국민임대  1330       1995.0  126.918489  37.124146

상위 인덱스                    geometry  2020총합  2021총합  2022총합  2023총합 년 평균 total  \
구분
0       POINT (126.83465 37.20698)   962.0  1020.0   976.0   965.0     980.75
1       POINT (126.82979 37.21003)  1029.0  1058.0  1055.0   962.0    1026.00
2        POINT (126.8339 37.20903)   789.0   828.0   789.0   510.0     729.00
3       POINT (127.06113 37.21127)  1666.0  1672.0  1690.0  1596.0    1656.00
4       POINT (127.11516 37.21753)   801.0   812.0   821.0   768.0     800.50
5       POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0    1448.00
6        POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0    1177.00
7        POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0    1964.25
8       POINT (127.06918 37.19352)  3146.0  3160.0  3197.0  3028.0    3132.75
9       POINT (126.96074 37.21867)  1032.0  1006.0  1025.0   970.0    1008.25
10      POINT (126.94385 37.22175)   596.0   607.0   642.0   599.0     611.00
11      POINT (126.95216 37.22511)  1437.0  1410.0  1443.0  1432.0    1430.50
12      POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0     458.00
13      POINT (126.89634 37.09738)  1425.0  1420.0  1351.0  1670.0    1466.50
14       POINT (126.90622 37.1155)  1108.0  1202.0  1196.0  1133.0    1159.75
15      POINT (126.91564 37.12438)  1128.0  1100.0  1100.0  1085.0    1103.25
16      POINT (126.91849 37.12415)  1767.0  1697.0  1716.0  1678.0    1714.50

상위 인덱스     male   female drivable high_risk       총합       avg_rent      평  \
구분                                                                  10평 이하
0        590.50   390.25   964.75     16.00   3923.0  170000.000000      8
1        524.50   501.50   992.50     33.50   4104.0  196666.666667      4
2        406.00   323.00   715.50     13.50   2916.0  170000.000000      8
3        722.75   933.25  1563.50     92.50   6624.0  242000.000000      0
4        390.75   409.75   771.25     29.25   3202.0  168750.000000      5
5        620.00   828.00  1395.00     53.00   1448.0  168750.000000      5
6        610.00   567.00  1159.25     17.75   4708.0  333750.000000      3
7        930.75  1033.50  1844.50    119.75   7857.0  206666.666667      2
8       1385.75  1747.00  2982.75    150.00  12531.0  365000.000000      0
9        475.00   533.25   960.25     48.00   4033.0  175714.285714      2
10       322.25   288.75   594.25     16.75   2444.0  210000.000000      5
11       775.00   655.50  1403.00     27.50   5722.0  209375.000000      5
12       282.00   176.00   427.00     31.00    458.0  132727.272727      7
13       897.75   568.75  1455.50     11.00   5866.0  180000.000000      1
14       645.00   514.75  1143.75     16.00   4639.0  184444.444444      4
15       525.50   577.75  1070.00     33.25   4413.0  148181.818182      5
16       830.25   884.25  1664.25     50.25   6858.0  136666.666667      4

상위 인덱스               건당 평균 사용 시간 세대 평균 사용 건수 세대 평균 사용 시간 now
구분     20평 이하 30평 이하
0           7      1    3.377778    0.020405    0.068923   1
1           4      1    6.201923    0.007420    0.046019   0
2           7      1    2.419573    0.030725    0.074342   0
3           5      0    2.840959    0.034876    0.099081   1
4           3      0    5.269027    0.020918    0.110218   0
5           3      0    2.913146    0.021747    0.063352   1
6           3      2    3.547881    0.016706    0.059271   0
7           1      0    3.175537    0.033771    0.107241   1
8           1      1    3.459509    0.016975    0.058726   1
9           5      0    3.273514    0.027322    0.089440   0
10          7      1    3.777190    0.034809    0.131481   0
11         10      1    3.517846    0.041478    0.145915   1
12          4      0    9.500000    0.003341    0.031737   0
13          1      0    3.532934    0.010652    0.037632   0
14          4      1    3.111765    0.012077    0.037582   0
15          6      0    5.939189    0.005148    0.030574   0
16          5      0    5.266667    0.004887    0.025739   0

# 공유차량 진행 기간 (month) (사용 X)

In [ ]:
def month(df):
    # MultiIndex의 첫 번째 레벨에서 이름을 가져와 필터링
    tm_columns = [col for col in df.columns.get_level_values(0) if str(col).startswith('tm')]

    # 결측치가 아닌 값의 개수 계산
    df['months'] = df[tm_columns].notna().sum(axis=1)
    return df

In [ ]:
#month(HN_공공)
#month(HN_영구)
#month(HN_행복)
#month(HN_국민)
#month(HS_공공)
#month(HS_영구)
#month(HS_행복)
month(HS_국민)

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm   car_type car_cnt month  \
구분
0               0  C02347       855     2888       모닝어반     1.0  41.0
1               1  C01961       104      645        NaN     NaN  16.0
2               2  C02042       889     2151        NaN     NaN  37.0
3               3  C01569      1377     3912       더뉴레이     1.0  41.0
4              12  C02194       565     2977        NaN     NaN  37.0
5              13  C02512       426     1241       올뉴K3     1.0  19.0
6              17  C02413       637     2260        NaN     NaN  31.0
7              19  C01873      2142     6802  모닝어반/올뉴K3     2.0  41.0
8              21  C01571      1630     5639  더뉴레이/올뉴K3     2.0  41.0
9              22  C01574       925     3028        NaN     NaN  37.0
10             24  C02140      1324     5001        NaN     NaN  37.0
11             25  C02139      1653     5815       올뉴모닝     1.0  41.0
12             27  C02562         6       57        NaN     NaN   4.0
13             30  C02049       501     1770        NaN     NaN  27.0
14             31  C01973       510     1587        NaN     NaN  34.0
15             32  C01588       148      879        NaN     NaN  25.0
16             33  C01589       195     1027        NaN     NaN  30.0

상위 인덱스      m_cnt        m_tm  type   noh parking_slot         lon        lat  \
구분
0       20.853659   70.439024  국민임대  1022       1533.0  126.834651  37.206978
1        6.500000   40.312500  국민임대   876       1314.0  126.829787  37.210028
2       24.027027   58.135135  국민임대   782       1173.0  126.833895  37.209028
3       33.585366   95.414634  국민임대   963       1444.5  127.061128  37.211268
4       15.270270   80.459459  국민임대   730       1095.0  127.115160  37.217529
5       22.421053   65.315789  국민임대  1031       1546.5  127.105712  37.211973
6       20.548387   72.903226  국민임대  1230       1845.0  127.121299  37.164322
7       52.243902  165.902439  국민임대  1547       2320.5  127.121597  37.206009
8       39.756098  137.536585  국민임대  2342       3513.0  127.069179  37.193522
9       25.000000   81.837838  국민임대   915       1372.5  126.960738  37.218666
10      35.783784  135.162162  국민임대  1028       1542.0  126.943852  37.221747
11      40.317073  141.829268  국민임대   972       1458.0  126.952162  37.225114
12       1.500000   14.250000  국민임대   449        673.5  126.876172  37.244215
13      18.555556   65.555556  국민임대  1742       2613.0  126.896338  37.097377
14      15.000000   46.676471  국민임대  1242       1863.0  126.906221  37.115500
15       5.920000   35.160000  국민임대  1150       1725.0  126.915635  37.124382
16       6.500000   34.233333  국민임대  1330       1995.0  126.918489  37.124146

상위 인덱스                    geometry  2020총합  2021총합  2022총합  2023총합 년 평균 total  \
구분
0       POINT (126.83465 37.20698)   962.0  1020.0   976.0   965.0     980.75
1       POINT (126.82979 37.21003)  1029.0  1058.0  1055.0   962.0    1026.00
2        POINT (126.8339 37.20903)   789.0   828.0   789.0   510.0     729.00
3       POINT (127.06113 37.21127)  1666.0  1672.0  1690.0  1596.0    1656.00
4       POINT (127.11516 37.21753)   801.0   812.0   821.0   768.0     800.50
5       POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0    1448.00
6        POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0    1177.00
7        POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0    1964.25
8       POINT (127.06918 37.19352)  3146.0  3160.0  3197.0  3028.0    3132.75
9       POINT (126.96074 37.21867)  1032.0  1006.0  1025.0   970.0    1008.25
10      POINT (126.94385 37.22175)   596.0   607.0   642.0   599.0     611.00
11      POINT (126.95216 37.22511)  1437.0  1410.0  1443.0  1432.0    1430.50
12      POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0     458.00
13      POINT (126.89634 37.09738)  1425.0  1420.0  1351.0  1670.0    1466.50
14       POINT (126.90622 37.1155)  1108.0  1202.0  1196.0  1133.0    1159.75
15      POINT (126.91564 37.12438)  1128.0  1100.0  1100.0  1085.0    1103.25
16      POINT (126.91849 37.12415)  1767.0  1697.0  1716.0  1678.0    1714.50

상위 인덱스     male   female drivable high_risk       총합       avg_rent      평  \
구분                                                                  10평 이하
0        590.50   390.25   964.75     16.00   3923.0  170000.000000      8
1        524.50   501.50   992.50     33.50   4104.0  196666.666667      4
2        406.00   323.00   715.50     13.50   2916.0  170000.000000      8
3        722.75   933.25  1563.50     92.50   6624.0  242000.000000      0
4        390.75   409.75   771.25     29.25   3202.0  168750.000000      5
5        620.00   828.00  1395.00     53.00   1448.0  168750.000000      5
6        610.00   567.00  1159.25     17.75   4708.0  333750.000000      3
7        930.75  1033.50  1844.50    119.75   7857.0  206666.666667      2
8       1385.75  1747.00  2982.75    150.00  12531.0  365000.000000      0
9        475.00   533.25   960.25     48.00   4033.0  175714.285714      2
10       322.25   288.75   594.25     16.75   2444.0  210000.000000      5
11       775.00   655.50  1403.00     27.50   5722.0  209375.000000      5
12       282.00   176.00   427.00     31.00    458.0  132727.272727      7
13       897.75   568.75  1455.50     11.00   5866.0  180000.000000      1
14       645.00   514.75  1143.75     16.00   4639.0  184444.444444      4
15       525.50   577.75  1070.00     33.25   4413.0  148181.818182      5
16       830.25   884.25  1664.25     50.25   6858.0  136666.666667      4

상위 인덱스               건당 평균 사용 시간 세대 평균 사용 건수 세대 평균 사용 시간 now months
구분     20평 이하 30평 이하
0           7      1    3.377778    0.020405    0.068923   1    0.0
1           4      1    6.201923    0.007420    0.046019   0    0.0
2           7      1    2.419573    0.030725    0.074342   0    0.0
3           5      0    2.840959    0.034876    0.099081   1    0.0
4           3      0    5.269027    0.020918    0.110218   0    0.0
5           3      0    2.913146    0.021747    0.063352   1    0.0
6           3      2    3.547881    0.016706    0.059271   0    0.0
7           1      0    3.175537    0.033771    0.107241   1    0.0
8           1      1    3.459509    0.016975    0.058726   1    0.0
9           5      0    3.273514    0.027322    0.089440   0    0.0
10          7      1    3.777190    0.034809    0.131481   0    0.0
11         10      1    3.517846    0.041478    0.145915   1    0.0
12          4      0    9.500000    0.003341    0.031737   0    0.0
13          1      0    3.532934    0.010652    0.037632   0    0.0
14          4      1    3.111765    0.012077    0.037582   0    0.0
15          6      0    5.939189    0.005148    0.030574   0    0.0
16          5      0    5.266667    0.004887    0.025739   0    0.0

In [ ]:
HN_1 = pd.concat([HN_공공, HN_영구, HN_행복, HN_국민], axis=0, ignore_index=True)
HS_1 = pd.concat([HS_공공, HS_영구, HS_행복, HS_국민], axis=0, ignore_index=True)

In [ ]:
HS_1

상위 인덱스 Unnamed: 0 blck_cd total_cnt total_tm                 car_type car_cnt  \
구분
0               5  C01890       937     2590                     올뉴모닝     1.0
1               6  C02014      1486     4975                     올뉴K3     1.0
2               7  C02015      1581     4013                     더뉴레이     1.0
3               8  C02329      1326     3669                     더뉴레이     1.0
4               9  C02160      1243     4510                     더뉴레이     1.0
5              10  C02246      1256     3463                     더뉴레이     1.0
6              14  C02512       426     1241                     올뉴K3     1.0
7              16  C02413       637     2260                      NaN     NaN
8              20  C01873      2142     6802                모닝어반/올뉴K3     2.0
9              28  C02562         6       57                      NaN     NaN
10              4  C02333      2090     6514                더뉴레이/올뉴모닝     2.0
11             11  C02109      1018     2824                     더뉴레이     1.0
12             15  C02421      5951    20057  니로 하이브리드/모닝어반/모닝어반/올뉴K3     4.0
13             18  C02404      1780     7263                모닝어반/올뉴K3     2.0
14             23  C02360       799     3847                     올뉴모닝     1.0
15             26  C02296      2009     6278                    더뉴스파크     1.0
16             29  C02553        18       30                      NaN     NaN
17              0  C02347       855     2888                     모닝어반     1.0
18              1  C01961       104      645                      NaN     NaN
19              2  C02042       889     2151                      NaN     NaN
20              3  C01569      1377     3912                     더뉴레이     1.0
21             12  C02194       565     2977                      NaN     NaN
22             13  C02512       426     1241                     올뉴K3     1.0
23             17  C02413       637     2260                      NaN     NaN
24             19  C01873      2142     6802                모닝어반/올뉴K3     2.0
25             21  C01571      1630     5639                더뉴레이/올뉴K3     2.0
26             22  C01574       925     3028                      NaN     NaN
27             24  C02140      1324     5001                      NaN     NaN
28             25  C02139      1653     5815                     올뉴모닝     1.0
29             27  C02562         6       57                      NaN     NaN
30             30  C02049       501     1770                      NaN     NaN
31             31  C01973       510     1587                      NaN     NaN
32             32  C01588       148      879                      NaN     NaN
33             33  C01589       195     1027                      NaN     NaN

상위 인덱스 month       m_cnt        m_tm  type   noh parking_slot         lon  \
구분
0       41.0   22.853659   63.170732  공공임대   754       1131.0  127.103636
1       41.0   36.243902  121.341463  공공임대   876       1314.0  127.126406
2       41.0   38.560976   97.878049  공공임대   882       1323.0  127.118188
3       38.0   34.894737   96.552632  공공임대   740       1110.0  127.123518
4       41.0   30.317073  110.000000  공공임대   924       1386.0  127.127443
5       41.0   30.634146   84.463415  공공임대   856       1284.0  127.094051
6       19.0   22.421053   65.315789  영구임대   359        538.5  127.105712
7       31.0   20.548387   72.903226  영구임대   538        807.0  127.121299
8       41.0   52.243902  165.902439  영구임대   600        900.0  127.121597
9        4.0    1.500000   14.250000  영구임대   203        304.5  126.876172
10      41.0   50.975610  158.878049  행복주택   816       1224.0  127.094684
11      41.0   24.829268   68.878049  행복주택   608        912.0  127.091382
12      35.0  170.028571  573.057143  행복주택  1640       2460.0  127.105411
13      40.0   44.500000  181.575000  행복주택   900       1350.0  127.121766
14      41.0   19.487805   93.829268  행복주택   608        912.0  126.909779
15      41.0   49.000000  153.121951  행복주택   602        903.0  126.951258
16       5.0    3.600000    6.000000  행복주택   440        660.0  126.876783
17      41.0   20.853659   70.439024  국민임대  1022       1533.0  126.834651
18      16.0    6.500000   40.312500  국민임대   876       1314.0  126.829787
19      37.0   24.027027   58.135135  국민임대   782       1173.0  126.833895
20      41.0   33.585366   95.414634  국민임대   963       1444.5  127.061128
21      37.0   15.270270   80.459459  국민임대   730       1095.0  127.115160
22      19.0   22.421053   65.315789  국민임대  1031       1546.5  127.105712
23      31.0   20.548387   72.903226  국민임대  1230       1845.0  127.121299
24      41.0   52.243902  165.902439  국민임대  1547       2320.5  127.121597
25      41.0   39.756098  137.536585  국민임대  2342       3513.0  127.069179
26      37.0   25.000000   81.837838  국민임대   915       1372.5  126.960738
27      37.0   35.783784  135.162162  국민임대  1028       1542.0  126.943852
28      41.0   40.317073  141.829268  국민임대   972       1458.0  126.952162
29       4.0    1.500000   14.250000  국민임대   449        673.5  126.876172
30      27.0   18.555556   65.555556  국민임대  1742       2613.0  126.896338
31      34.0   15.000000   46.676471  국민임대  1242       1863.0  126.906221
32      25.0    5.920000   35.160000  국민임대  1150       1725.0  126.915635
33      30.0    6.500000   34.233333  국민임대  1330       1995.0  126.918489

상위 인덱스        lat                    geometry  2020총합  2021총합  2022총합  2023총합  \
구분
0       37.176328  POINT (127.10364 37.17633)  1573.0  1579.0  1587.0  1556.0
1       37.183691  POINT (127.12641 37.18369)  1012.0  1060.0  1053.0   876.0
2       37.173069  POINT (127.11819 37.17307)  1688.0  1759.0  1763.0  1765.0
3       37.175706  POINT (127.12352 37.17571)   356.0   392.0   388.0   618.0
4       37.186354  POINT (127.12744 37.18635)   847.0   851.0   870.0   875.0
5       37.161979  POINT (127.09405 37.16198)  1229.0  1400.0  1397.0  1390.0
6       37.211973  POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0
7       37.164322   POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0
8       37.206009   POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0
9       37.244215  POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0
10      37.163702   POINT (127.09468 37.1637)   754.0   746.0   746.0   733.0
11      37.185811  POINT (127.09138 37.18581)   376.0   395.0   415.0   383.0
12      37.213554  POINT (127.10541 37.21355)   814.0  1425.0  1459.0  1294.0
13      37.166277  POINT (127.12177 37.16628)   483.0   657.0   642.0   676.0
14      37.087628  POINT (126.90978 37.08763)   205.0   310.0   314.0   313.0
15      37.229013  POINT (126.95126 37.22901)   363.0   329.0   309.0   288.0
16      37.243062  POINT (126.87678 37.24306)     0.0     0.0     0.0   398.0
17      37.206978  POINT (126.83465 37.20698)   962.0  1020.0   976.0   965.0
18      37.210028  POINT (126.82979 37.21003)  1029.0  1058.0  1055.0   962.0
19      37.209028   POINT (126.8339 37.20903)   789.0   828.0   789.0   510.0
20      37.211268  POINT (127.06113 37.21127)  1666.0  1672.0  1690.0  1596.0
21      37.217529  POINT (127.11516 37.21753)   801.0   812.0   821.0   768.0
22      37.211973  POINT (127.10571 37.21197)     0.0     0.0     0.0  1448.0
23      37.164322   POINT (127.1213 37.16432)     8.0  1443.0  1642.0  1615.0
24      37.206009   POINT (127.1216 37.20601)  1832.0  1961.0  2040.0  2024.0
25      37.193522  POINT (127.06918 37.19352)  3146.0  3160.0  3197.0  3028.0
26      37.218666  POINT (126.96074 37.21867)  1032.0  1006.0  1025.0   970.0
27      37.221747  POINT (126.94385 37.22175)   596.0   607.0   642.0   599.0
28      37.225114  POINT (126.95216 37.22511)  1437.0  1410.0  1443.0  1432.0
29      37.244215  POINT (126.87617 37.24422)     0.0     0.0     0.0   458.0
30      37.097377  POINT (126.89634 37.09738)  1425.0  1420.0  1351.0  1670.0
31      37.115500   POINT (126.90622 37.1155)  1108.0  1202.0  1196.0  1133.0
32      37.124382  POINT (126.91564 37.12438)  1128.0  1100.0  1100.0  1085.0
33      37.124146  POINT (126.91849 37.12415)  1767.0  1697.0  1716.0  1678.0

상위 인덱스 년 평균 total     male   female drivable high_risk       총합  \
구분
0         1573.75   790.25   783.50  1571.75      2.00   6295.0
1         1000.25   493.50   506.75   998.75      1.50   4001.0
2         1743.75   871.00   872.75  1743.75      0.00   6975.0
3          438.50   200.25   238.25   438.50      0.00   1754.0
4          860.75   425.00   435.75   860.75      0.00   3443.0
5         1354.00   677.25   676.75  1354.00      0.00   5416.0
6         1448.00   620.00   828.00  1395.00     53.00   1448.0
7         1177.00   610.00   567.00  1159.25     17.75   4708.0
8         1964.25   930.75  1033.50  1844.50    119.75   7857.0
9          458.00   282.00   176.00   427.00     31.00    458.0
10         744.75   444.50   300.25   744.75      0.00   2979.0
11         392.25   233.75   158.50   392.25      0.00   1569.0
12        1248.00   636.50   611.50  1234.50     13.50   4992.0
13         614.50   354.75   259.75   610.50      4.00   2458.0
14         285.50   211.50    74.00   285.50      0.00   1142.0
15         322.25   190.75   131.50   322.25      0.00   1289.0
16         398.00   242.00   156.00   388.00     10.00    398.0
17         980.75   590.50   390.25   964.75     16.00   3923.0
18        1026.00   524.50   501.50   992.50     33.50   4104.0
19         729.00   406.00   323.00   715.50     13.50   2916.0
20        1656.00   722.75   933.25  1563.50     92.50   6624.0
21         800.50   390.75   409.75   771.25     29.25   3202.0
22        1448.00   620.00   828.00  1395.00     53.00   1448.0
23        1177.00   610.00   567.00  1159.25     17.75   4708.0
24        1964.25   930.75  1033.50  1844.50    119.75   7857.0
25        3132.75  1385.75  1747.00  2982.75    150.00  12531.0
26        1008.25   475.00   533.25   960.25     48.00   4033.0
27         611.00   322.25   288.75   594.25     16.75   2444.0
28        1430.50   775.00   655.50  1403.00     27.50   5722.0
29         458.00   282.00   176.00   427.00     31.00    458.0
30        1466.50   897.75   568.75  1455.50     11.00   5866.0
31        1159.75   645.00   514.75  1143.75     16.00   4639.0
32        1103.25   525.50   577.75  1070.00     33.25   4413.0
33        1714.50   830.25   884.25  1664.25     50.25   6858.0

상위 인덱스       avg_rent      평               건당 평균 사용 시간 세대 평균 사용 건수  \
구분                    10평 이하 20평 이하 30평 이하
0       710000.000000      0      0      2    2.764141    0.030310
1       505000.000000      0      4      2    3.347914    0.041374
2       385000.000000      3      4      3    2.538267    0.043720
3       454444.444444      1      5      3    2.766968    0.047155
4       567500.000000      0      2      2    3.628319    0.032811
5       430000.000000      1      3      2    2.757166    0.035788
6       168750.000000      5      3      0    2.913146    0.062454
7       333750.000000      3      3      2    3.547881    0.038194
8       206666.666667      2      1      0    3.175537    0.087073
9       132727.272727      7      4      0    9.500000    0.007389
10      430000.000000      1      3      2    3.116746    0.062470
11      175000.000000      1      1      0    2.774067    0.040838
12      168750.000000      5      3      0    3.370358    0.103676
13      343000.000000      3      5      2    4.080337    0.049444
14      125000.000000      1      1      0    4.814768    0.032052
15      228000.000000      4      5      1    3.124938    0.081395
16      137500.000000      5      3      0    1.666667    0.008182
17      170000.000000      8      7      1    3.377778    0.020405
18      196666.666667      4      4      1    6.201923    0.007420
19      170000.000000      8      7      1    2.419573    0.030725
20      242000.000000      0      5      0    2.840959    0.034876
21      168750.000000      5      3      0    5.269027    0.020918
22      168750.000000      5      3      0    2.913146    0.021747
23      333750.000000      3      3      2    3.547881    0.016706
24      206666.666667      2      1      0    3.175537    0.033771
25      365000.000000      0      1      1    3.459509    0.016975
26      175714.285714      2      5      0    3.273514    0.027322
27      210000.000000      5      7      1    3.777190    0.034809
28      209375.000000      5     10      1    3.517846    0.041478
29      132727.272727      7      4      0    9.500000    0.003341
30      180000.000000      1      1      0    3.532934    0.010652
31      184444.444444      4      4      1    3.111765    0.012077
32      148181.818182      5      6      0    5.939189    0.005148
33      136666.666667      4      5      0    5.266667    0.004887

상위 인덱스 세대 평균 사용 시간 now months
구분
0         0.083781   1    NaN
1         0.138518   1    NaN
2         0.110973   1    NaN
3         0.130477   1    NaN
4         0.119048   1    NaN
5         0.098672   1    NaN
6         0.181938   1    NaN
7         0.135508   0    NaN
8         0.276504   1    NaN
9         0.070197   0    NaN
10        0.194703   1    NaN
11        0.113286   1    NaN
12        0.349425   1    NaN
13        0.201750   1    NaN
14        0.154324   1    NaN
15        0.254355   1    NaN
16        0.013636   0    NaN
17        0.068923   1    0.0
18        0.046019   0    0.0
19        0.074342   0    0.0
20        0.099081   1    0.0
21        0.110218   0    0.0
22        0.063352   1    0.0
23        0.059271   0    0.0
24        0.107241   1    0.0
25        0.058726   1    0.0
26        0.089440   0    0.0
27        0.131481   0    0.0
28        0.145915   1    0.0
29        0.031737   0    0.0
30        0.037632   0    0.0
31        0.037582   0    0.0
32        0.030574   0    0.0
33        0.025739   0    0.0

In [ ]:
HN_1.to_csv('HN_1.csv', index=False, encoding='utf-8-sig')

In [ ]:
HS_1.to_csv('HS_1.csv', index=False, encoding='utf-8-sig')